#!/bin/bash
#PBS -P w97
#PBS -q normal
#PBS -l ncpus=8
#PBS -l mem=70Gb
#PBS -l walltime=01:45:00
#PBS -l jobfs=1gb
#PBS -l wd
#PBS -l storage=gdata/hh5+gdata/w97+gdata/ua8
#PBS -M matt.grant@unsw.edu.au
#PBS -m abe
#PBS -N creating_new_simp_vs_1911_simp_perf_metrics
 
module use /g/data/hh5/public/modules
module load conda/analysis3
 
#python3 
python3 /home/561/mg5624/RF_project/RF_model/model_analytics.py